from pathlib import Path
root=Path(__file__).parent
p=root/'public/index.html';s=p.read_text();a=s.index('<form class="form" id="auth-form">');b=s.index('</dialog>',a);s=s[:a]+'''<p class="description">Sign in with GitHub to publish a rating and review. Playing and reporting glitches never require an account.</p><button class="primary" id="github-signin" style="width:100%;margin-top:15px">Continue with GitHub →</button><p class="status" id="auth-status" role="status"></p><p class="hint">Your player name and review are public. Your GitHub password is entered only on GitHub.</p>'''+s[b:];p.write_text(s)
p=root/'public/app.js';s=p.read_text().replace('let signup=false,rating=0;','let rating=0;');a=s.index('function openAuth()');b=s.index('for(let i=1;i<=5;i++)',a);s=s[:a]+'''function openAuth(){$('auth-status').textContent='';$('auth-dialog').showModal();$('github-signin').focus();}
$('account').addEventListener('click',async()=>{if(api.session){try{await api.signOut();}catch{}finally{accountUI();}}else openAuth();});$('write-review').addEventListener('click',()=>{if(!api.session)openAuth();else{$('review-form').hidden=false;$('review-text').focus();}});$('close-auth').onclick=()=>$('auth-dialog').close();$('github-signin').onclick=()=>{try{api.signInGitHub();}catch(error){$('auth-status').textContent=error.message;}};
'''+s[b:];p.write_text(s)
p=root/'public/api.js';s=p.read_text();a=s.index(' async signIn(email');b=s.index(' async signOut()',a);s=s[:a]+''' signInGitHub(){if(!this.configured)throw Error('Community sign-in is not connected yet.');const url=new URL(CONFIG.supabaseUrl+'/auth/v1/authorize');url.searchParams.set('provider','github');url.searchParams.set('redirect_to',new URL('.',location.href).href);location.assign(url.href);}
'''+s[b:];p.write_text(s)
p=root/'backend/schema.sql';s=p.read_text().replace("u.raw_user_meta_data->>'display_name'","coalesce(u.raw_user_meta_data->>'user_name',u.raw_user_meta_data->>'preferred_username',u.raw_user_meta_data->>'display_name')");p.write_text(s)
p=root/'README.md';s=p.read_text().replace('Keep email confirmation enabled, set Site URL','Enable the GitHub Auth provider (using a free GitHub OAuth application and its callback URL from Supabase), set Site URL').replace('Set the public app registration minimum password to 10 characters. Confirm SMTP/email sending limits for the chosen project; use a configured provider when needed for public registrations.','The site uses GitHub OAuth, so visitors do not need a separate password or an email-delivery service. Configure the OAuth secret only in Supabase Auth settings, never the repository.').replace('a real email-confirmed account','a real GitHub sign-in');p.write_text(s)
p=root/'public/privacy.html';s=p.read_text().replace('Your account email and password are not published.','Your account email is not published. Sign-in is handled by GitHub and Supabase; this website does not ask for or store your GitHub password.');p.write_text(s)
p=root/'tests.mjs';s=p.read_text();s=s.replace("await api.signIn('player@example.com','test-password');assert(api.session.access_token);","globalThis.location={href:'https://incasedgames.github.io/',assign:url=>calls.push({oauth:url})};api.signInGitHub();assert(calls.at(-1).oauth.includes('provider=github'));assert(calls.at(-1).oauth.includes('redirect_to=https%3A%2F%2Fincasedgames.github.io%2F'));api.store({access_token:'test-auth',refresh_token:'test-refresh',expires_in:3600,user:{id:'test'}});assert(api.session.access_token);");p.write_text(s)
